#  _               _                            _                          
# | |__   ___  ___| |_      ___ _ __   ___  ___(_)_ __ ___   ___ _ __  ___ 
# | '_ \ / _ \/ __| __|____/ __| '_ \ / _ \/ __| | '_ ` _ \ / _ \ '_ \/ __|
# | | | | (_) \__ \ ||_____\__ \ |_) |  __/ (__| | | | | | |  __/ | | \__ \
# |_| |_|\___/|___/\__|    |___/ .__/ \___|\___|_|_| |_| |_|\___|_| |_|___/
#                              |_|                                         
- hosts: all
  become: true
  become_user: root
  remote_user: deploy
  vars:
    destination: "~/"
    servicelist: ["postfix", "dovecot"]
    journalopts: "-r -p3 -S today --no-pager -n 100"
  tasks:
    - name: host-specimens | Prefix value should be generated
      register: prefix
      changed_when: false
      shell: date '+%F'

    - name: host-specimens | uptime command should be executed
      shell: >
        uptime > ./uptime-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./uptime-{{ prefix.stdout }}"

    - name: host-specimens | ps command should be executed
      shell: >
        ps auxwwf > ./ps-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./ps-{{ prefix.stdout }}"

    - name: host-specimens | top command should be executed
      shell: >
        top -bc -n 1 > ./top-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./top-{{ prefix.stdout }}"

    - name: host-specimens | free command should be executed
      shell: >
        free -m > ./free-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./free-{{ prefix.stdout }}"

    - name: host-specimens | df command should be executed
      shell: >
        df -h > ./df-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./df-{{ prefix.stdout }}"

    - name: host-specimens | netstat -nat command should be executed
      shell: >
        netstat -nat > ./netstat-nat-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./netstat-nat-{{ prefix.stdout }}"

    - name: host-specimens | netstat -nar command should be executed
      shell: >
        netstat -nar > ./netstat-nar-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./netstat-nar-{{ prefix.stdout }}"

    - name: host-specimens | ls /tmp command should be executed
      shell: >
        ls -laF /tmp > ./ls-tmp-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./ls-tmp-{{ prefix.stdout }}"

    - name: host-specimens | journalctl -k command should be executed
      shell: >
        journalctl {{ journalopts }} -k > ./journalctl-kernel-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./journalctl-kernel-{{ prefix.stdout }}"

    - name: host-specimens | systemctl command should be executed
      shell: >
        journalctl {{ journalopts }} -u {{ item }} > ./journalctl-{{ item }}-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./journalctl-{{ item }}-{{ prefix.stdout }}"
      with_items: "{{ servicelist }}"

    - name: host-specimens | systemctl command should be executed
      shell: >
        systemctl status {{ item }} > ./systemctl-{{ item }}-{{ prefix.stdout }}
      args:
        chdir:   "{{ destination }}"
        creates: "./systemctl-{{ item }}-{{ prefix.stdout }}"
      with_items: "{{ servicelist }}"

